// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemInformaticPensiune.Data;

#nullable disable

namespace SistemInformaticPensiune.Migrations
{
    [DbContext(typeof(SistemInformaticPensiuneContext))]
    [Migration("20251230162349_UpdateTableNames")]
    partial class UpdateTableNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemInformaticPensiune.Models.Camera", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Numar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int?>("TipCameraID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TipCameraID");

                    b.ToTable("Camera");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prenume")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.Facilitate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NumeFacilitate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Facilitate");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.FacilitateCamera", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CameraID")
                        .HasColumnType("int");

                    b.Property<int>("FacilitateID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CameraID");

                    b.HasIndex("FacilitateID");

                    b.ToTable("FacilitateCamera");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.Rezervare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CameraID")
                        .HasColumnType("int");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataSfarsit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateInceput")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CameraID");

                    b.HasIndex("ClientID");

                    b.ToTable("Rezervare");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.TipCamera", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TipCamera");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.Camera", b =>
                {
                    b.HasOne("SistemInformaticPensiune.Models.TipCamera", "TipCamera")
                        .WithMany("Camere")
                        .HasForeignKey("TipCameraID");

                    b.Navigation("TipCamera");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.FacilitateCamera", b =>
                {
                    b.HasOne("SistemInformaticPensiune.Models.Camera", "Camera")
                        .WithMany("FacilitatiCamera")
                        .HasForeignKey("CameraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemInformaticPensiune.Models.Facilitate", "Facilitate")
                        .WithMany("FacilitatiCamera")
                        .HasForeignKey("FacilitateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Facilitate");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.Rezervare", b =>
                {
                    b.HasOne("SistemInformaticPensiune.Models.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraID");

                    b.HasOne("SistemInformaticPensiune.Models.Client", "Client")
                        .WithMany("Rezervari")
                        .HasForeignKey("ClientID");

                    b.Navigation("Camera");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.Camera", b =>
                {
                    b.Navigation("FacilitatiCamera");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.Client", b =>
                {
                    b.Navigation("Rezervari");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.Facilitate", b =>
                {
                    b.Navigation("FacilitatiCamera");
                });

            modelBuilder.Entity("SistemInformaticPensiune.Models.TipCamera", b =>
                {
                    b.Navigation("Camere");
                });
#pragma warning restore 612, 618
        }
    }
}
